var JAK={NAME:"JAK",_idCnt:0,idGenerator:function(){this._idCnt=1E7>this._idCnt?this._idCnt:0;var a="m"+(new Date).getTime().toString(16)+"m"+this._idCnt.toString(16);this._idCnt++;return a}};String.prototype.lpad=function(a,b){for(var c=a||"0",d=b||2,e="";e.length<d-this.length;)e+=c;e=e.substring(0,d-this.length);return e+this.toString()};String.prototype.rpad=function(a,b){for(var c=a||"0",d=b||2,e="";e.length<d-this.length;)e+=c;e=e.substring(0,d-this.length);return this.toString()+e};
String.prototype.CS_ALPHABET="0123456789A\u00c1BC\u010cD\u010eE\u011a\u00c9FGHCHI\u00cdJKLMN\u0147O\u00d3PQR\u0158S\u0160T\u0164U\u00da\u016eVWXY\u00ddZ\u017da\u00e1bc\u010dd\u010fe\u011b\u00e9fghchi\u00edjklmn\u0148o\u00f3pqr\u0159s\u0161t\u0165u\u00fa\u016fvwxy\u00fdz\u017e";
String.prototype.localeCSCompare=function(a){a+="";if(this+""===a)return 0;if(this.length<a.length)return-a.localeCSCompare(this);for(var b=0,c=0,d=a.length,e="",f="",g=0,h=0;b<d;){e=a.charAt(b);f=this.charAt(c);"c"==f.toLowerCase()&&(g=this.substring(c,c+2),"ch"==g||"CH"==g)&&(c++,f=g);"c"==e.toLowerCase()&&(g=a.substring(b,b+2),"ch"==g||"CH"==g)&&(b++,e=g);g=this.CS_ALPHABET.indexOf(e);h=this.CS_ALPHABET.indexOf(f);if(e!=f)break;b++;c++}return b==d?1:g==h?f.localeCompare(e):-1==h?-1:-1==g?1:h-g};
Date.prototype.toISOString||function(){function a(a){a=String(a);1===a.length&&(a="0"+a);return a}Date.prototype.toISOString=function(){return this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"."+String((this.getUTCMilliseconds()/1E3).toFixed(3)).slice(2,5)+"Z"}}();Date.prototype._dayNames="Pond\u011bl\u00ed \u00dater\u00fd St\u0159eda \u010ctvrtek P\u00e1tek Sobota Ned\u011ble".split(" ");
Date.prototype._dayNamesShort="Po \u00dat St \u010ct P\u00e1 So Ne".split(" ");Date.prototype._monthNames="Leden \u00danor B\u0159ezen Duben Kv\u011bten \u010cerven \u010cervenec Srpen Z\u00e1\u0159\u00ed \u0158\u00edjen Listopad Prosinec".split(" ");Date.prototype._monthNamesShort="Led \u00dano B\u0159e Dub Kv\u011b \u010cer \u010crc Srp Z\u00e1\u0159 \u0158\u00edj Lis Pro".split(" ");
Date.prototype.format=function(a){for(var b={1:"st",2:"nd",3:"rd",21:"st",22:"nd",23:"rd",31:"st"},c="",d=!1,e=0;e<a.length;e++){var f=a.charAt(e);if(d)d=!1,c+=f;else switch(f){case "\\":d?(d=!1,c+=f):d=!0;break;case "d":c+=this.getDate().toString().lpad();break;case "j":c+=this.getDate();break;case "w":c+=this.getDay();break;case "N":c+=this.getDay()||7;break;case "S":f=this.getDate();c+=b[f]||"th";break;case "D":c+=this._dayNamesShort[(this.getDay()||7)-1];break;case "l":c+=this._dayNames[(this.getDay()||
7)-1];break;case "z":var g=this.getTime(),f=new Date(g);f.setDate(1);f.setMonth(0);f=g-f.getTime();c+=f/864E5;break;case "W":var f=new Date(this.getFullYear(),this.getMonth(),this.getDate()),h=f.getDay()||7;f.setDate(f.getDate()+(4-h));g=f.getFullYear();h=Math.floor((f.getTime()-(new Date(g,0,1,-6)).getTime())/864E5);c+=(1+Math.floor(h/7)).toString().lpad();break;case "m":c+=(this.getMonth()+1).toString().lpad();break;case "n":c+=this.getMonth()+1;break;case "M":c+=this._monthNamesShort[this.getMonth()];
break;case "F":c+=this._monthNames[this.getMonth()];break;case "t":var g=this.getTime(),k=this.getMonth(),f=new Date(g);do h=f.getDate(),g+=864E5,f=new Date(g);while(k==f.getMonth());c+=h;break;case "L":f=new Date(this.getTime());f.setDate(1);f.setMonth(1);f.setDate(29);c+=1==f.getMonth()?"1":"0";break;case "Y":c+=this.getFullYear().toString().lpad();break;case "y":c+=this.getFullYear().toString().lpad().substring(2);break;case "a":c+=12>this.getHours()?"am":"pm";break;case "A":c+=12>this.getHours()?
"AM":"PM";break;case "G":c+=this.getHours();break;case "H":c+=this.getHours().toString().lpad();break;case "g":c+=this.getHours()%12;break;case "h":c+=(this.getHours()%12).toString().lpad();break;case "i":c+=this.getMinutes().toString().lpad();break;case "s":c+=this.getSeconds().toString().lpad();break;case "Z":c+=-60*this.getTimezoneOffset();break;case "O":case "P":g=this.getTimezoneOffset()/-60;h=Math.abs(g).toString().lpad();"P"==f&&(h+=":");h+="00";c+=(0<=g?"+":"-")+h;break;case "U":c+=this.getTime()/
1E3;break;case "u":c+="0";break;case "c":c+=arguments.callee.call(this,"Y-m-d")+"T"+arguments.callee.call(this,"H:i:sP");break;case "r":c+=arguments.callee.call(this,"D, j M Y H:i:s O");break;default:c+=f}}return c};Function.prototype.bind||(Function.prototype.bind=function(a){var b=this,c=Array.prototype.slice.call(arguments,1);return function(){return b.apply(a,c.concat(Array.prototype.slice.call(arguments)))}});Date.now||(Date.now=function(){return+new Date});String.prototype.trim=function(){return this.match(/^\s*([\s\S]*?)\s*$/)[1]};
String.trim||(String.trim=function(a){return String.prototype.trim.call(a)});Object.create||(Object.create=function(){function a(){}var b=Object.prototype.hasOwnProperty;return function(c){if("object"!=typeof c)throw TypeError("Object prototype may only be an Object or null");a.prototype=c;var d=new a;a.prototype=null;if(1<arguments.length){var e=Object(arguments[1]),f;for(f in e)b.call(e,f)&&(d[f]=e[f])}return d}}());
Object.keys||(Object.keys=function(){var a=Object.prototype.hasOwnProperty,b=!{toString:null}.propertyIsEnumerable("toString"),c="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),d=c.length;return function(e){if("object"!==typeof e&&("function"!==typeof e||null===e))throw new TypeError("Object.keys called on non-object");var f=[],g;for(g in e)a.call(e,g)&&f.push(g);if(b)for(g=0;g<d;g++)a.call(e,c[g])&&f.push(c[g]);return f}}());
Array.isArray||(Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)});
"function"!==typeof Array.prototype.reduce&&(Array.prototype.reduce=function(a,b){if(null===this||"undefined"===typeof this)throw new TypeError("Array.prototype.reduce called on null or undefined");if("function"!==typeof a)throw new TypeError(a+" is not a function");var c,d,e=this.length>>>0,f=!1;1<arguments.length&&(d=b,f=!0);for(c=0;e>c;++c)this.hasOwnProperty(c)&&(f?d=a(d,this[c],c,this):(d=this[c],f=!0));if(!f)throw new TypeError("Reduce of empty array with no initial value");return d});
"function"!==typeof Array.prototype.reduceRight&&(Array.prototype.reduceRight=function(a,b){if(null===this||"undefined"===typeof this)throw new TypeError("Array.prototype.reduceRight called on null or undefined");if("function"!==typeof a)throw new TypeError(a+" is not a function");var c,d;c=this.length>>>0;var e=!1;1<arguments.length&&(d=b,e=!0);for(c-=1;-1<c;--c)this.hasOwnProperty(c)||(e?d=a(d,this[c],c,this):(d=this[c],e=!0));if(!e)throw new TypeError("Reduce of empty array with no initial value");
return d});Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){var c=this.length,d=b||0;for(0>d&&(d+=c);d<c;d++)if(d in this&&this[d]===a)return d;return-1});Array.indexOf||(Array.indexOf=function(a,b,c){return Array.prototype.indexOf.call(a,b,c)});Array.prototype.lastIndexOf||(Array.prototype.lastIndexOf=function(a,b){var c=this.length,d=void 0===b?c-1:b;for(0>d&&(d+=c);-1<d;d--)if(d in this&&this[d]===a)return d;return-1});
Array.lastIndexOf||(Array.lastIndexOf=function(a,b,c){return 2<arguments.length?Array.prototype.lastIndexOf.call(a,b,c):Array.prototype.lastIndexOf.call(a,b)});Array.prototype.forEach||(Array.prototype.forEach=function(a,b){for(var c=this.length,d=0;d<c;d++)d in this&&a.call(b,this[d],d,this)});Array.forEach||(Array.forEach=function(a,b,c){Array.prototype.forEach.call(a,b,c)});
Array.prototype.every||(Array.prototype.every=function(a,b){for(var c=this.length,d=0;d<c;d++)if(d in this&&!a.call(b,this[d],d,this))return!1;return!0});Array.every||(Array.every=function(a,b,c){return Array.prototype.every.call(a,b,c)});Array.prototype.some||(Array.prototype.some=function(a,b){for(var c=this.length,d=0;d<c;d++)if(d in this&&a.call(b,this[d],d,this))return!0;return!1});Array.some||(Array.some=function(a,b,c){return Array.prototype.some.call(a,b,c)});
Array.prototype.map||(Array.prototype.map=function(a,b){for(var c=this.length,d=Array(c),e=0;e<c;e++)e in this&&(d[e]=a.call(b,this[e],e,this));return d});Array.map||(Array.map=function(a,b,c){return Array.prototype.map.call(a,b,c)});Array.prototype.filter||(Array.prototype.filter=function(a,b){for(var c=this.length,d=[],e=0;e<c;e++)if(e in this){var f=this[e];a.call(b,f,e,this)&&d.push(f)}return d});Array.filter||(Array.filter=function(a,b,c){return Array.prototype.filter.call(a,b,c)});
"classList"in document.documentElement||!window.Element||function(){function a(a){this._element=a;if(a.className!=this._classCache&&(this._classCache=a.className)){a=this._classCache.replace(/^\s+|\s+$/g,"").split(/\s+/);for(var b=0;b<a.length;b++)e.call(this,a[b])}}var b=Array.prototype,c=b.indexOf,d=b.slice,e=b.push,f=b.splice,g=b.join;window.DOMTokenList=a;a.prototype={add:function(a){this.contains(a)||(e.call(this,a),a=d.call(this,0),this._element.className=a.join(" "))},contains:function(a){return-1!=
c.call(this,a)},item:function(a){return this[a]||null},remove:function(a){a=c.call(this,a);-1!=a&&(f.call(this,a,1),a=d.call(this,0),this._element.className=a.join(" "))},toString:function(){return g.call(this," ")},toggle:function(a){if(-1==c.call(this,a))return this.add(a),!0;this.remove(a);return!1}};(function(a,b,c){Object.defineProperty?Object.defineProperty(a,b,{get:c}):a.__defineGetter__(b,c)})(Element.prototype,"classList",function(){return new a(this)})}();
(function(){var a=document.createElement("_");a.classList.add("c1","c2");if(!a.classList.contains("c2")){var b=function(a){var b=DOMTokenList.prototype[a];DOMTokenList.prototype[a]=function(a){var c,d=arguments.length;for(c=0;c<d;c++)a=arguments[c],b.call(this,a)}};b("add");b("remove")}a.classList.toggle("c3",!1);if(a.classList.contains("c3")){var c=DOMTokenList.prototype.toggle;DOMTokenList.prototype.toggle=function(a,b){return 1 in arguments&&!this.contains(a)===!b?b:c.call(this,a)}}a=null})();
JAK.ClassMaker={};JAK.ClassMaker.VERSION="5.1";JAK.ClassMaker.NAME="JAK.ClassMaker";JAK.ClassMaker.makeClass=function(a){a=this._makeDefaultParams(a);return this._addConstructorProperties(function(){if(this.$constructor)return this.$constructor.apply(this,arguments)},a)};JAK.ClassMaker.makeSingleton=function(a){a=this._makeDefaultParams(a);var b=function(){throw Error("Cannot instantiate singleton class");};b._instance=null;b.getInstance=this._getInstance;return this._addConstructorProperties(b,a)};
JAK.ClassMaker.makeInterface=function(a){a=this._makeDefaultParams(a);return this._addConstructorProperties(function(){throw Error("Cannot instantiate interface");},a)};JAK.ClassMaker.makeStatic=function(a){a=this._makeDefaultParams(a);var b={};b.VERSION=a.VERSION;b.NAME=a.NAME;return b};
JAK.ClassMaker._makeDefaultParams=function(a){if("EXTEND"in a){if(!a.EXTEND)throw Error("Cannot extend non-exist class");if("function"!=typeof a.EXTEND)throw Error("Cannot extend non-function");if(!("NAME"in a.EXTEND))throw Error("Cannot extend non-JAK class");}a.NAME=a.NAME||!1;a.VERSION=a.VERSION||"1.0";a.EXTEND=a.EXTEND||!1;a.IMPLEMENT=a.IMPLEMENT||[];a.DEPEND=a.DEPEND||[];a.IMPLEMENT instanceof Array||(a.IMPLEMENT=[a.IMPLEMENT]);this._preMakeTests(a);return a};
JAK.ClassMaker._preMakeTests=function(a){if(!a.NAME)throw Error("No NAME passed to JAK.ClassMaker.makeClass()");var b=!1;if(b=this._testDepend(a.DEPEND))throw Error("Dependency error in class "+a.NAME+" ("+b+")");};JAK.ClassMaker._addConstructorProperties=function(a,b){for(var c in b)a[c]=b[c];this._setInheritance(a);a.prototype.constructor=a;a.prototype.$super=this._$super;return a};
JAK.ClassMaker._getInstance=function(){this._instance||(this._instance=Object.create(this.prototype),"$constructor"in this.prototype&&this._instance.$constructor());return this._instance};JAK.ClassMaker._setInheritance=function(a){a.EXTEND&&this._makeInheritance(a,a.EXTEND);for(var b=0;b<a.IMPLEMENT.length;b++)this._makeInheritance(a,a.IMPLEMENT[b],!0)};
JAK.ClassMaker._makeInheritance=function(a,b,c){for(var d in b.prototype){var e=b.prototype[d];"function"!=typeof e||e.owner||(e.owner=b)}if(c)for(d in b.prototype)a.prototype[d]="object"==typeof b.prototype[d]?JSON.parse(JSON.stringify(b.prototype[d])):b.prototype[d];else for(d in a.prototype=Object.create(b.prototype),b.prototype)"object"==typeof b.prototype[d]&&(a.prototype[d]=JSON.parse(JSON.stringify(b.prototype[d])))};
JAK.ClassMaker._testDepend=function(a){for(var b=0;b<a.length;b++){var c=a[b];if(!c.sClass)return"Unsatisfied dependency";if(!c.ver)return"Version not specified in dependency";var d=c.sClass.VERSION.split(".")[0],e=c.ver.split(".")[0];if(d!=e)return"Version conflict in "+c.sClass.NAME}return!1};
JAK.ClassMaker._$super=function(){var a=arguments.callee.caller;if(!a)throw Error("Function.prototype.caller not supported");var b=a.owner||this.constructor,c=!1,d;for(d in b.prototype)if(b.prototype[d]==a){c=d;break}if(!c)throw Error("Cannot find supplied method in constructor");a=b.EXTEND;if(!a)throw Error("No super-class available");if(!a.prototype[c])throw Error("Super-class doesn't have method '"+c+"'");return a.prototype[c].apply(this,arguments)};
JAK.Events=JAK.ClassMaker.makeStatic({NAME:"JAK.Events",VERSION:"3.3"});JAK.Events._events={};JAK.Events._domReadyCallbacks=[];JAK.Events.onDomReady=function(a,b){var c="function"==typeof b?b:a[b];a&&(c=c.bind(a));if("complete"==document.readyState)return setTimeout(c,0);this._domReadyCallbacks.length||document.addEventListener("DOMContentLoaded",function(){for(;this._domReadyCallbacks.length;)this._domReadyCallbacks.shift()()}.bind(this),!1);this._domReadyCallbacks.push(c)};
JAK.Events.addListener=function(a,b,c,d,e){c=c||window;e=e||!1;var f=JAK.idGenerator(),g=c;if(d)if("string"==typeof d){if("function"!=typeof c[d])throw Error("Events.addListener: arguments[3] must be method of arguments[2]");g=function(b){c[d](b,a,f)}}else g=function(b){d.call(c,b,a,f)};else"function"==typeof c?g=function(b){c(b,a,f)}:document.addEventListener||(g=function(b){b.currentTarget=a;c.handleEvent(b)});this._addListener(a,b,g,e);this._events[f]={elm:a,type:b,action:g,capture:e};return f};
JAK.Events._addListener=function(a,b,c,d){b=b.split(" ");for(var e=0;e<b.length;e++){var f=b[e];a.addEventListener?a.addEventListener(f,c,d):a.attachEvent("on"+f,c)}};JAK.Events.removeListener=function(a){if(!(a in this._events))throw Error("Cannot remove non-existent event ID '"+a+"'");var b=this._events[a];this._removeListener(b.elm,b.type,b.action,b.capture);delete this._events[a]};
JAK.Events._removeListener=function(a,b,c,d){b=b.split(" ");for(var e=0;e<b.length;e++){var f=b[e];a.removeEventListener?a.removeEventListener(f,c,d):a.detachEvent("on"+f,c)}};JAK.Events.removeListeners=function(a){for(;a.length;)this.removeListener(a.shift())};JAK.Events.removeAllListeners=function(){for(var a in this._events)this.removeListener(a)};JAK.Events.stopEvent=function(a){a=a||window.event;a.stopPropagation?a.stopPropagation():a.cancelBubble=!0};
JAK.Events.cancelDef=function(a){a=a||window.event;a.preventDefault?a.preventDefault():a.returnValue=!1};JAK.Events.getTarget=function(a){a=a||window.event;return a.target||a.srcElement};JAK.Browser=JAK.ClassMaker.makeStatic({NAME:"JAK.Browser",VERSION:"3.0"});JAK.Browser.platform="";JAK.Browser.client="";JAK.Browser.version=0;JAK.Browser.agent="";JAK.Browser.mouse={};this.ieCompatibilityView=!1;
JAK.Browser._getPlatform=function(){return-1!=this._agent.indexOf("Windows Phone")?"wph":-1!=this._agent.indexOf("iPhone")||-1!=this._agent.indexOf("iPod")||-1!=this._agent.indexOf("iPad")?"ios":-1!=this._agent.indexOf("Android")?"and":-1!=this._agent.indexOf("X11")||-1!=this._agent.indexOf("Linux")?"nix":-1!=this._agent.indexOf("Mac")?"mac":-1!=this._agent.indexOf("Win")?"win":"oth"};
JAK.Browser._getClient=function(){return window.opera?"opera":-1!=this._agent.indexOf("Edge")?"edge":window.chrome?"chrome":"all"in document&&"systemLanguage"in navigator?"ie":document.getAnonymousElementByAttribute||"mozPaintCount"in window?"gecko":-1!=this._agent.indexOf("KHTML")?"KDE"==this._vendor?"konqueror":-1!=this._vendor.indexOf("Apple")?"safari":"oth":"oth"};
JAK.Browser._getMouse=function(){return"ie"==JAK.Browser.client&&9>parseFloat(JAK.Browser.version)?{left:1,middle:4,right:2}:{left:0,middle:1,right:2}};JAK.Browser._getVersion=function(){var a="_get_"+this.client+"_ver";return"function"==typeof this[a]?this[a]():"0"};
JAK.Browser._get_ie_ver=function(){return Function.prototype.call?!window.ActiveXObject&&"ActiveXObject"in window?"11":"draggable"in document.createElement("div")?"10":document.addEventListener?"9":"[object JSON]"===Object.prototype.toString.call(window.JSON)?"8":window.XMLHttpRequest?"7":"object"==typeof document.doctype?"6":"5.5":"5.0"};JAK.Browser._get_opera_ver=function(){return window.opera.version?window.opera.version():document.createComment?"7":"6"};
JAK.Browser._get_gecko_ver=function(){return"textOverflow"in document.createElement("div").style?"7":window.EventSource?"6":"onloadend"in new XMLHttpRequest?"5":history.pushState?"4":void 0===document.getBoxObjectFor?"3.6":navigator.geolocation?"3.5":document.getElementsByClassName?"3":window.external?"2":"1.5"};JAK.Browser._get_konqueror_ver=function(){var a=this._agent.indexOf("KHTML")+6,a=this._agent.substring(a),b=a.indexOf(" ");return a.substring(0,b-2)};
JAK.Browser._get_safari_ver=function(){var a=this._agent.match(/version\/([0-9]+)/i);return a?a[1]:"3"};JAK.Browser._get_chrome_ver=function(){var a=this._agent.match(/Chrome\/([0-9]+)/i);return a?a[1]:null};
JAK.Browser.isOld=function(){if("ie"==this.client&&7>=parseFloat(this.version)||"opera"==this.client&&9.5>parseFloat(this.version)||"gecko"==this.client&&2>parseFloat(this.version)||"konqueror"==this.client&&3.5>parseFloat(this.version)||!document.documentElement||!document.documentElement.addEventListener&&!document.documentElement.attachEvent)return!0;var a=function(){};return a.call&&a.apply?!1:!0};
JAK.Browser._testIeCompatibilityView=function(a,b){return"ie"==a&&b.match(/Trident\/([4-9])/)?-1<b.indexOf("MSIE 7.0"):!1};JAK.Browser.getBrowser=function(){this._agent=this.agent=navigator.userAgent;this._platform=navigator.platform;this._vendor=navigator.vendor;this.platform=this._getPlatform();this.client=this._getClient();this.version=this._getVersion();this.mouse=this._getMouse();this.ieCompatibilityView=this._testIeCompatibilityView(this.client,this._agent)};JAK.Browser.getBrowser();
JAK.DOM=JAK.ClassMaker.makeStatic({NAME:"JAK.DOM",VERSION:"5.0"});JAK.cel=function(a,b,c,d){a=(d||document).createElement(a);b&&(a.className=b);c&&(a.id=c);return a};JAK.mel=function(a,b,c,d){a=(d||document).createElement(a);if(b)for(var e in b)a[e]=b[e];c&&JAK.DOM.setStyle(a,c);return a};JAK.ctext=function(a,b){return(b||document).createTextNode(a)};JAK.gel=function(a,b){var c=b||document;return"string"==typeof a?c.getElementById(a):a};
JAK.query=function(a,b){for(var c=(b||document).querySelectorAll(a),d=Array(c.length),e=0;e<c.length;e++)d[e]=c[e];return d};JAK.DOM.append=function(){for(var a=0;a<arguments.length;a++)for(var b=arguments[a],c=b[0],d=1;d<b.length;d++)c.appendChild(b[d])};JAK.DOM.hasClass=function(a,b){return a.classList.contains(b)};JAK.DOM.addClass=function(a,b){b.split(" ").forEach(function(b){a.classList.add(b)})};JAK.DOM.removeClass=function(a,b){a.classList.remove(b)};JAK.DOM.clear=function(a){for(;a.firstChild;)a.removeChild(a.firstChild)};
JAK.DOM.getDocSize=function(){var a=0,b=0;if("BackCompat"!=document.compatMode){if(document.documentElement.clientWidth&&"opera"!=JAK.Browser.client?(a=document.documentElement.clientWidth,b=document.documentElement.clientHeight):"opera"==JAK.Browser.client&&(9.5>parseFloat(JAK.Browser.version)?(a=document.body.clientWidth,b=document.body.clientHeight):(a=document.documentElement.clientWidth,b=document.documentElement.clientHeight)),"safari"==JAK.Browser.client||"konqueror"==JAK.Browser.client)b=
window.innerHeight}else a=document.body.clientWidth,b=document.body.clientHeight;return{width:a,height:b}};
JAK.DOM.getBoxPosition=function(a,b){var c=0,d=0,e=b||a.ownerDocument.body;if(a.getBoundingClientRect&&!b)return c=document.documentElement,d=a.getBoundingClientRect(),e=JAK.DOM.getBoxScroll(a),{left:d.left+e.x-c.clientLeft,top:d.top+e.y-c.clientTop};for(;a&&a!=e;){c+=a.offsetTop;d+=a.offsetLeft;if(("gecko"==JAK.Browser.client&&3>JAK.Browser.version||"safari"==JAK.Browser.client)&&"fixed"==JAK.DOM.getStyle(a,"position")){e=JAK.DOM.getScrollPos();c+=e.y;d+=e.x;break}a=a.offsetParent}return{top:c,left:d}};
JAK.DOM.getPosition=function(a,b){var c=b||a.ownerDocument.documentElement,d=a.getBoundingClientRect(),c=c.getBoundingClientRect();return{top:d.top-c.top,left:d.left-c.left}};JAK.DOM.getPortBoxPosition=function(a,b,c){var d=JAK.DOM.getBoxPosition(a,b);a=JAK.DOM.getBoxScroll(a,b,c);d.left-=a.x;d.top-=a.y;return{left:d.left,top:d.top}};JAK.DOM.getPortPosition=function(a){a=JAK.DOM.getPosition(a);var b=JAK.DOM.getScrollPos();return{left:a.left-b.x,top:a.top-b.y}};
JAK.DOM.getBoxScroll=function(a,b,c){var d=0,e=0,f=a.parentNode;a=b||a.ownerDocument.documentElement;for(b=!1;;)if("opera"==JAK.Browser.client&&f.parentNode&&"block"!=JAK.DOM.getStyle(f,"display"))f=f.parentNode;else if(f==document.body&&f.scrollLeft==f.parentNode.scrollLeft&&f.scrollTop==f.parentNode.scrollTop)f=f.parentNode;else{c&&"fixed"==JAK.DOM.getStyle(f,"position")&&(b=!0);b||(d+=f.scrollLeft,e+=f.scrollTop);if(f==a)break;f=f.parentNode;if(!f)break}return{x:d,y:e}};
JAK.DOM.getScrollPos=function(){if(document.documentElement.scrollTop||document.documentElement.scrollLeft)var a=document.documentElement.scrollLeft,b=document.documentElement.scrollTop;else document.body.scrollTop||document.body.scrollLeft?(a=document.body.scrollLeft,b=document.body.scrollTop):b=a=0;return{x:a,y:b}};JAK.DOM.getStyle=function(a,b){if(document.defaultView&&document.defaultView.getComputedStyle){var c=a.ownerDocument.defaultView.getComputedStyle(a,"");return c?c[b]:!1}return a.currentStyle[b]};
JAK.DOM.setStyle=function(a,b){for(var c in b)a.style[c]=b[c]};JAK.DOM.writeStyle=function(a){var b=JAK.mel("style",{type:"text/css"});b.styleSheet?b.styleSheet.cssText=a:b.appendChild(JAK.ctext(a));a=document.getElementsByTagName("head");a.length?a=a[0]:(a=JAK.cel("head"),document.documentElement.appendChild(a));a.appendChild(b);return b};
JAK.DOM.elementsHider=function(a,b,c){function d(b){for(var c=!1;b.parentNode&&b!=document;)b==a&&(c=!0),b=b.parentNode;return c}var e=b;e||(e=["select","object","embed","iframe"]);var f=arguments.callee.hidden;f&&(f.forEach(function(a){a.style.visibility="visible"}),arguments.callee.hidden=[]);if("hide"==c){"string"==typeof a&&(a=JAK.gel(a));var f=[],g=this.getBoxPosition(a);g.width=a.offsetWidth+g.left;g.height=a.offsetHeight+g.top;for(var h=0;h<e.length;++h)for(var k=document.getElementsByTagName(e[h]),
l=0;l<k.length;++l){var m=this.getBoxPosition(k[l]);d(k[l])||(m.width=k[l].offsetWidth+m.left,m.height=k[l].offsetHeight+m.top,g.left>m.width||g.width<m.left||g.top>m.height||g.height<m.top||(k[l].style.visibility="hidden",f.push(k[l])))}arguments.callee.hidden=f}};JAK.DOM.getElementsByClass=function(a,b,c){return this.arrayFromCollection((b||document).querySelectorAll((c||"")+"."+a))};JAK.DOM.arrayFromCollection=function(a){var b=[];try{b=Array.prototype.slice.call(a)}catch(c){for(var d=0;d<a.length;d++)b.push(a[d])}finally{return b}};
JAK.DOM.separateCode=function(a){var b=[];return[a.replace(/<script.*?>([\s\S]*?)<\/script>/g,function(a,d){b.push(d);return""}),b.join("\n")]};JAK.DOM.shiftBox=function(a){var b=0,c=0,d=JAK.DOM.getBoxPosition(a),e=JAK.DOM.getScrollPos();d.left-=e.x;d.top-=e.y;var e=JAK.DOM.getDocSize(),f=a.offsetWidth;a=d.top+a.offsetHeight-e.height;0<a&&(d.top-=a,c-=a);a=d.left+f-e.width;0<a&&(d.left-=a,b-=a);a=d.top;0>a&&(d.top-=a,c-=a);a=d.left;0>a&&(d.left-=a,b-=a);return[b,c]};
JAK.DOM.scrollbarWidth=function(){var a=JAK.mel("div",null,{width:"50px",height:"50px",overflow:"hidden",position:"absolute",left:"-200px"}),b=JAK.mel("div",null,{height:"100px"});a.appendChild(b);document.body.insertBefore(a,document.body.firstChild);b=a.clientWidth+parseInt(JAK.DOM.getStyle(a,"paddingLeft"))+parseInt(JAK.DOM.getStyle(a,"paddingRight"));JAK.DOM.setStyle(a,{overflowY:"scroll"});var c=a.clientWidth+parseInt(JAK.DOM.getStyle(a,"paddingLeft"))+parseInt(JAK.DOM.getStyle(a,"paddingRight"));
document.body.removeChild(a);return b-c};JAK.DOM.findParent=function(a,b){for(var c=(b||"").match(/[#.]?[a-z0-9_-]+/ig)||[],d=a.parentNode;d&&d!=document;){for(var e=!0,f=0;f<c.length;f++){var g=c[f];switch(g.charAt(0)){case "#":d.id!=g.substring(1)&&(e=!1);break;case ".":JAK.DOM.hasClass(d,g.substring(1))||(e=!1);break;default:d.nodeName.toLowerCase()!=g.toLowerCase()&&(e=!1)}}if(e)return d;d=d.parentNode}return null};JAK.ObjLib=JAK.ClassMaker.makeClass({NAME:"ObjLib",VERSION:"3.1"});
JAK.ObjLib.prototype.reSetOptions=function(){};JAK.ObjLib.prototype.pretty=function(a){return a};JAK.ObjLib.prototype.serialize=function(a){return JSON.stringify(a)};JAK.ObjLib.prototype.unserialize=function(a){return JSON.parse(a)};JAK.ObjLib.prototype.match=function(a,b){return JSON.stringify(a)==JSON.stringify(b)};JAK.ObjLib.prototype.copy=function(a){return JSON.parse(JSON.stringify(a))};JAK.ObjLib.prototype.arrayCopy=function(a){return this.copy(a)};
JAK.Request=JAK.ClassMaker.makeClass({NAME:"JAK.Request",VERSION:"2.0"});JAK.Request.XML=0;JAK.Request.TEXT=1;JAK.Request.JSONP=2;JAK.Request.BINARY=3;JAK.Request.supportsCrossOrigin=function(){return"opera"==JAK.Browser.client&&12>parseFloat(JAK.Browser.version)||"ie"==JAK.Browser.client&&8>JAK.Browser.version||"gecko"==JAK.Browser.client&&3.5>parseFloat(JAK.Browser.version)?!1:!0};JAK.Request.supportsUpload=function(){return window.XMLHttpRequest&&!!(new XMLHttpRequest).upload};
JAK.Request.prototype.$constructor=function(a,b){this._NEW=0;this._SENT=1;this._DONE=2;this._ABORTED=3;this._TIMEOUT=4;this._PROGRESS=5;this._xhr=null;this._callback="";this._script=null;this._type=a;this._headers={};this._callbacks={};this._state=this._NEW;this._xdomain=!1;this._promise=new JAK.Promise;this._handleProgress=!1;this._options={async:!0,timeout:0,method:"get"};for(var c in b)this._options[c]=b[c];if(this._type==JAK.Request.JSONP){if("post"==this._options.method.toLowerCase())throw Error("POST not supported in JSONP mode");
if(!this._options.async)throw Error("Sync not supported in JSONP mode");}};JAK.Request.prototype.$destructor=function(){this._state==this._SENT&&this.abort();this._xhr=null};JAK.Request.prototype.setHeaders=function(a){if(this._type==JAK.Request.JSONP)throw Error("Request headers not supported in JSONP mode");for(var b in a)this._headers[b]=a[b]};
JAK.Request.prototype.getHeaders=function(){if(this._state!=this._DONE)throw Error("Response headers not available");if(this._type==JAK.Request.JSONP)throw Error("Response headers not supported in JSONP mode");var a={},b=this._xhr.getAllResponseHeaders();if(b)for(var b=b.split(/[\r\n]/),c=0;c<b.length;c++)if(b[c]){var d=b[c].match(/^([^:]+): *(.*)$/);a[d[1]]=d[2]}return a};
JAK.Request.prototype.send=function(a,b){if(this._state!=this._NEW)throw Error("Request already sent");this._state=this._SENT;this._userCallback(this);switch(this._type){case JAK.Request.XML:case JAK.Request.TEXT:case JAK.Request.BINARY:this._sendXHR(a,b);break;case JAK.Request.JSONP:this._sendScript(a,b);break;default:throw Error("Unknown request type");}return this._promise};
JAK.Request.prototype.abort=function(){if(this._state!=this._SENT)return!1;this._state=this._ABORTED;this._xhr&&this._xhr.abort();this._userCallback(this);this._promise.reject({type:"abort",request:this});return!0};JAK.Request.prototype.setCallback=function(a,b){this._setCallback(a,b,this._DONE);return this};JAK.Request.prototype.setSendCallback=function(a,b){this._setCallback(a,b,this._SENT);return this};JAK.Request.prototype.setAbortCallback=function(a,b){this._setCallback(a,b,this._ABORTED);return this};
JAK.Request.prototype.setTimeoutCallback=function(a,b){this._setCallback(a,b,this._TIMEOUT);return this};JAK.Request.prototype.setProgressCallback=function(a,b){this._handleProgress=!0;this._setCallback(a,b,this._PROGRESS);return this};JAK.Request.prototype._setCallback=function(a,b,c){this._callbacks[c]=[a,b]};
JAK.Request.prototype._sendXHR=function(a,b){if(window.XMLHttpRequest){this._xhr=new XMLHttpRequest;var c=a.match(/^(https?\:)?\/\/(.*?)\//);if(c&&c[2]!=location.host&&window.XDomainRequest&&!this._xhr.upload){if(this._type==JAK.Request.BINARY)throw Error("XDomainRequest does not support BINARY mode");if(this._type==JAK.Request.XML)throw Error("XDomainRequest does not support XML mode");this._xdomain=!0;this._xhr=new XDomainRequest}}else if(window.ActiveXObject)this._xhr=new ActiveXObject("Microsoft.XMLHTTP");
else throw Error("No XHR available");this._xdomain?(this._xhr.onload=this._onXDomainRequestLoad.bind(this),this._xhr.onerror=this._onXDomainRequestError.bind(this)):this._xhr.onreadystatechange=this._onReadyStateChange.bind(this);var d;if("get"==this._options.method.toLowerCase())c=this._buildURL(a,b),d=null;else{c=a;d=this._serializeData(b);var e=!1,f;for(f in this._headers)if("content-type"==f.toLowerCase()){e=!0;break}e||this.setHeaders({"Content-Type":"application/x-www-form-urlencoded"})}if(this._type==
JAK.Request.BINARY)if(this._xhr.overrideMimeType)this._xhr.overrideMimeType("text/plain; charset=x-user-defined");else if("ie"==JAK.Browser.client)this._buildVBS();else throw Error("This browser does not support binary transfer");this._handleProgress&&this._xhr.upload&&JAK.Events.addListener(this._xhr.upload,"progress",this,"_progressCallback");this._xhr.open(this._options.method,c,this._options.async);this._options.async&&(this._xhr.withCredentials=this._options.withCredentials);for(f in this._headers)this._xhr.setRequestHeader(f,
this._headers[f]);this._xhr.send(d);this._options.timeout&&setTimeout(this._timeout.bind(this),this._options.timeout);this._options.async||this._onReadyStateChange()};JAK.Request.prototype._sendScript=function(a,b){var c=b||{};this._callback="callback"+JAK.idGenerator();c.callback=this._callback;a=this._buildURL(a,c);window[this._callback]=this._scriptCallback.bind(this);this._script=JAK.mel("script",{type:"text/javascript",src:a});document.body.insertBefore(this._script,document.body.firstChild)};
JAK.Request.prototype._buildURL=function(a,b){var c=this._serializeData(b);return c.length?-1==a.indexOf("?")?a+"?"+c:a+"&"+c:a};JAK.Request.prototype._serializeData=function(a){if("string"==typeof a||window.File&&a instanceof File)return a;if(!a)return"";var b=[],c;for(c in a){var d=a[c];d instanceof Array||(d=[d]);for(var e=0;e<d.length;e++)b.push(encodeURIComponent(c)+"="+encodeURIComponent(d[e]))}return b.join("&")};
JAK.Request.prototype._onReadyStateChange=function(){if(this._state!=this._ABORTED&&this._state!=this._TIMEOUT&&4==this._xhr.readyState){this._xhr.onreadystatechange=null;var a=this._xhr.status,b;if(this._type==JAK.Request.BINARY)if(b=[],this._xhr.overrideMimeType)for(var c=this._xhr.responseText,d=c.length,e=0;e<d;e++)b.push(c.charCodeAt(e)&255);else for(d=VBS_getLength(this._xhr.responseBody),e=0;e<d;e++)b.push(VBS_getByte(this._xhr.responseBody,e));else b=this._type==JAK.Request.XML?this._xhr.responseXML:
this._xhr.responseText;this._done(b,a)}};JAK.Request.prototype._onXDomainRequestLoad=function(){if(this._state!=this._ABORTED){var a=this._xhr.responseText;if(this._type==JAK.Request.XML){var b=new ActiveXObject("Microsoft.XMLDOM");b.async=!1;b.loadXML(a);a=b}this._done(a,200)}};JAK.Request.prototype._onXDomainRequestError=function(){this._state!=this._ABORTED&&(this._state=this._ABORTED,this._userCallback(this),this._promise.reject({type:"error",request:this}))};
JAK.Request.prototype._progressCallback=function(a){a=a.loaded/a.total;var b=this._state;this._state=this._PROGRESS;this._userCallback(a);this._state=b};JAK.Request.prototype._scriptCallback=function(a){this._script.parentNode.removeChild(this._script);this._script=null;try{delete window[this._callback]}catch(b){}this._state!=this._ABORTED&&this._done(a,200)};
JAK.Request.prototype._done=function(a,b){this._state!=this._DONE&&(this._state=this._DONE,this._userCallback(a,b,this),b?this._promise.fulfill({data:a,status:b,request:this}):this._promise.reject({type:"abort",request:this}))};JAK.Request.prototype._timeout=function(){this._state==this._SENT&&(this._state=this._TIMEOUT,this._xhr&&this._xhr.abort(),this._userCallback(this),this._promise.reject({type:"timeout",request:this}))};
JAK.Request.prototype._userCallback=function(a){var b=this._callbacks[this._state];if(b){var c=b[0]||window,b=b[1];c&&"string"==typeof b&&(b=c[b]);b||(b=c,c=window);b.apply(c,arguments)}};JAK.Request.prototype._buildVBS=function(){var a=JAK.mel("script",{type:"text/vbscript"});a.text="Function VBS_getByte(data, pos)\nVBS_getByte = AscB(MidB(data, pos+1,1))\nEnd Function\nFunction VBS_getLength(data)\nVBS_getLength = LenB(data)\nEnd Function";document.getElementsByTagName("head")[0].appendChild(a)};
JAK.Signals=JAK.ClassMaker.makeClass({NAME:"JAK.Signals",VERSION:"2.1"});JAK.Signals.prototype.$constructor=function(){this._myHandleFolder={};this._myIdFolder={}};
JAK.Signals.prototype.addListener=function(a,b,c,d){var e=JAK.idGenerator(),f=[],g={eOwner:a,eFunction:c,eSender:d};b=b.split(" ");for(var h=0;h<b.length;h++){var k=b[h];k in this._myHandleFolder||(this._myHandleFolder[k]={});var k=this._myHandleFolder[k],l=!0,m;for(m in k){var p=k[m];p.eFunction==c&&p.eOwner==a&&p.eSender==d&&(l=!1)}l&&(k[e]=g,f.push(k))}return f.length?(this._myIdFolder[e]=f,e):null};
JAK.Signals.prototype.removeListener=function(a){var b=this._myIdFolder[a];for(b||console.error("Cannot remove non-existent signal ID '"+a+"'");b.length;)delete b.pop()[a];delete this._myIdFolder[a]};JAK.Signals.prototype.removeListeners=function(a){for(;a.length;)this.removeListener(a.shift())};JAK.Signals.prototype.makeEvent=function(a,b,c){a={type:a,target:b,timeStamp:(new Date).getTime(),data:c&&"object"==typeof c?c:null};this._myEventHandler(a)};
JAK.Signals.prototype._myEventHandler=function(a){var b=[],c;for(c in this._myHandleFolder)if(c==a.type||"*"==c)for(var d in this._myHandleFolder[c]){var e=this._myHandleFolder[c][d];e.eSender&&e.eSender!=a.target||b.push(e)}for(c=0;c<b.length;c++)if(e=b[c],d=e.eOwner,e=e.eFunction,"string"==typeof e)d[e](a);else"function"==typeof e&&e(a)};JAK.signals=new JAK.Signals;JAK.ISignals=JAK.ClassMaker.makeInterface({NAME:"JAK.ISignals",VERSION:"2.1"});
JAK.ISignals.prototype.setInterface=function(a){if("object"==typeof this[a])return this[a];for(var b=this._owner;"undefined"==typeof b[a];){if("undefined"!=typeof b.TOP_LEVEL)throw Error("SetInterface:Interface not found");b=b._owner}return b[a]};JAK.ISignals.prototype.addListener=function(a,b,c){return this.getInterface().addListener(this,a,b,c)};JAK.ISignals.prototype.removeListener=function(a){return this.getInterface().removeListener(a)};JAK.ISignals.prototype.removeListeners=function(a){this.getInterface().removeListeners(a)};
JAK.ISignals.prototype.makeEvent=function(a,b){this.getInterface().makeEvent(a,this,b)};JAK.ISignals.prototype.getInterface=function(){return"object"==typeof this.signals?this.signals:JAK.signals};JAK.AbstractDecorator=JAK.ClassMaker.makeSingleton({NAME:"JAK.AbstractDecorator",VERSION:"2.0"});JAK.AbstractDecorator.prototype.decorate=function(a){a.$super=this._$super;a.__decorators||(a.__decorators=[]);a.__decorators.push(this);return a};
JAK.AbstractDecorator.prototype._$super=function(){var a=arguments.callee.caller;if(!a)throw Error("Function.prototype.caller not supported");for(var b=this.__decorators||[],c=null,d=null,e=b.length;e--;){var f=b[e];if(!c&&d&&d in f){c=f;break}for(var g in f)if(!d&&a==f[g]){d=g;break}}if(!d){c=a.owner||this.constructor;b=!1;for(d in c.prototype)c.prototype[d]==a&&(b=d);if(!b)throw Error("Cannot find supplied method in constructor");a=c.EXTEND;if(!a)throw Error("No super-class available");if(!a.prototype[b])throw Error("Super-class doesn't have method '"+
b+"'");return a.prototype[b].apply(this,arguments)}if(!(c||(c=this.constructor.prototype,d in c)))throw Error("Function '"+d+"' has no undecorated parent");return c[d].apply(this,arguments)};JAK.AutoDecorator=JAK.ClassMaker.makeSingleton({NAME:"JAK.AutoDecorator",VERSION:"1.0",EXTEND:JAK.AbstractDecorator});JAK.AutoDecorator.prototype.decorate=function(a){this.$super(a);var b=["constructor","$super","_$super","decorate"],c;for(c in this)-1==b.indexOf(c)&&(a[c]=this[c])};
JAK.IDecorable=JAK.ClassMaker.makeClass({NAME:"JAK.IDecorable",VERSION:"2.0",CLASS:"class"});JAK.IDecorable.prototype.decorate=function(a){for(var b=[this],c=1;c<arguments.length;c++)b.push(arguments[c]);c=a.getInstance();return c.decorate.apply(c,b)};JAK.Timekeeper=JAK.ClassMaker.makeSingleton({NAME:"JAK.Timekeeper",VERSION:"1.1"});
JAK.Timekeeper.prototype.$constructor=function(){this._listeners=[];this._running=0;this._tick=this._tick.bind(this);this._scheduler=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a,b){setTimeout(a,1E3/60)}};
JAK.Timekeeper.prototype.addListener=function(a,b,c){if(-1!=this._findListener(a))throw Error("This listener is already attached");a={what:a,method:b,count:c||1,bucket:0};a.bucket=a.count;this._listeners.push(a);2!=this._running&&(0==this._running&&this._schedule(),this._running=2);return this};
JAK.Timekeeper.prototype.removeListener=function(a){a=this._findListener(a);if(-1==a)throw Error("Cannot find listener to be removed");this._listeners.splice(a,1);this._listeners.length||(this._running=1);return this};JAK.Timekeeper.prototype._findListener=function(a){for(var b=0;b<this._listeners.length;b++)if(this._listeners[b].what==a)return b;return-1};
JAK.Timekeeper.prototype._tick=function(){1==this._running&&(this._running=0);if(0!=this._running){this._schedule();for(var a=0;a<this._listeners.length;a++){var b=this._listeners[a];b.bucket--;if(!b.bucket){b.bucket=b.count;var c=b.what;("string"==typeof b.method?c[b.method]:b.method).call(c)}}}};JAK.Timekeeper.prototype._schedule=function(){var a=this._scheduler;a(this._tick,null)};JAK.C=JAK.ClassMaker.makeClass({NAME:"JAK.C",VERSION:"1.0",IMPLEMENT:JAK.ISignals});
JAK.C.prototype.$constructor=function(){this.LIMIT=1E3;this.DEBUG=!1;this.REMOTE={active:!1,limit:10,what:["error"]};this._native=window.console;this._data=[];this._lost=0;this._defineLogMethod("log");this._defineLogMethod("info");this._defineLogMethod("warn");this._defineLogMethod("debug");this._defineLogMethod("error");this._defineLogMethod("dir")};JAK.C.prototype.clear=function(){this._lost=0;this._data=[];this.makeEvent("change")};JAK.C.prototype.getLost=function(){return this._lost};
JAK.C.prototype.getData=function(){return this._data};JAK.C.prototype._defineLogMethod=function(a){var b=this;this[a]=function(){return b._log(a,arguments)}};
JAK.C.prototype._log=function(a,b){for(this._data.push({type:a,args:b,ts:(new Date).getTime()});this._data.length>this.LIMIT;)this._data.shift(),this._lost++;this.REMOTE.active&&window.DOT&&-1<this.REMOTE.what.indexOf(a)&&this.REMOTE.limit&&(this.REMOTE.limit--,DOT.hit("error",{d:{type:a,args:b}}));if(this.DEBUG&&this._native){var c=this._native[a];return c||(c=this._native.log,c)?Function.prototype.apply.call(c,this._native,b):void 0}this.makeEvent("change")};!window.console&&(window.console=new JAK.C);
JAK.Promise=JAK.ClassMaker.makeClass({NAME:"JAK.Promise",VERSION:"1.0"});JAK.Promise.prototype.$constructor=function(a){this._state=0;this._value=null;this._cb={fulfilled:[],rejected:[]};this._thenPromises=[];a&&this._invokeResolver(a)};JAK.Promise.all=JAK.Promise.when=function(a){for(var b=new this,c=0,d=[],e=0;e<a.length;e++)c++,a[e].then(function(a,e){d[a]=e;c--;c||b.fulfill(d)}.bind(null,e),function(a){c=1/0;b.reject(a)});return b};
JAK.Promise.prototype.then=function(a,b){this._cb.fulfilled.push(a);this._cb.rejected.push(b);var c=new JAK.Promise;this._thenPromises.push(c);0<this._state&&setTimeout(this._processQueue.bind(this),0);return c};JAK.Promise.prototype["catch"]=function(a){return this.then(null,a)};JAK.Promise.prototype.fulfill=function(a){if(0!=this._state)return this;this._state=1;this._value=a;this._processQueue();return this};
JAK.Promise.prototype.reject=function(a){if(0!=this._state)return this;this._state=2;this._value=a;this._processQueue();return this};JAK.Promise.prototype.chain=function(a){return this.then(a.fulfill.bind(a),a.reject.bind(a))};JAK.Promise.prototype._processQueue=function(){for(;this._thenPromises.length;){var a=this._cb.fulfilled.shift(),b=this._cb.rejected.shift();this._executeCallback(1==this._state?a:b)}};
JAK.Promise.prototype._executeCallback=function(a){var b=this._thenPromises.shift();if("function"!=typeof a)1==this._state?b.fulfill(this._value):b.reject(this._value);else try{var c=a(this._value);c&&"function"==typeof c.then?c.then(function(a){b.fulfill(a)},function(a){b.reject(a)}):b.fulfill(c)}catch(d){window.console&&window.console.error&&console.error(d),b.reject(d)}};JAK.Promise.prototype._invokeResolver=function(a){try{a(this.fulfill.bind(this),this.reject.bind(this))}catch(b){this.reject(b)}};
(function(){var a=function(){for(var a=Array.prototype.slice.call(arguments),b=document.createDocumentFragment(),c,g;g=a.shift();)if("string"==typeof g)for(c=document.createElement("div"),c.innerHTML=g;c.firstChild;)b.appendChild(c.firstChild);else b.appendChild(g);return b},b={before:function(){var b=a.apply(this,arguments);this.parentNode.insertBefore(b,this)},after:function(){var b=a.apply(this,arguments);this.parentNode.insertBefore(b,this.nextSibling)},replaceWith:function(){if(this.parentNode){var b=
a.apply(this,arguments);this.parentNode.replaceChild(b,this)}},remove:function(){this.parentNode&&this.parentNode.removeChild(this)}},c=["before","after","replaceWith","remove"];["Element","DocumentType","CharacterData"].forEach(function(a){c.forEach(function(c){window[a]&&!window[a].prototype[c]&&(window[a].prototype[c]=b[c])})})})();
(function(){if(!document.addEventListener&&window.Element&&window.Event){Event.prototype.NONE=Event.NONE=0;Event.prototype.CAPTURING_PHASE=Event.CAPTURING_PHASE=1;Event.prototype.AT_TARGET=Event.AT_TARGET=2;Event.prototype.BUBBLING_PHASE=Event.BUBBLING_PHASE=3;Event.prototype.preventDefault=function(){!1!==this.cancelable&&(this.returnValue=!1)};Event.prototype.stopPropagation=function(){this.cancelBubble=!0};Event.prototype.stopImmediatePropagation=function(){this.__immediateStopped=this.cancelBubble=
!0};var a=function(a,b,c){for(var d=0;d<a.length;d++){var e=a[d];if(e.useCapture==c&&e.listener==b)return d}return-1},b=function(a,b,c){a.currentTarget=c;"function"==typeof b?b.call(c,a):b.handleEvent(a)},c=function(a,c,d){a.eventPhase=d;for(var e=0;e<c.length;e++){for(var f=c[e],g=[],h=(f.__events||{})[a.type]||[],n=0;n<h.length;n++){var q=h[n];q.useCapture&&d==Event.BUBBLING_PHASE||(q.useCapture||d!=Event.CAPTURING_PHASE)&&g.push(q.listener)}for(n=0;n<g.length;)try{for(;n<g.length;){var r=g[n++];
b(a,r,f);if(a.__immediateStopped)return!0}}catch(s){setTimeout(function(){throw s;},0)}if(a.cancelBubble)return!0}return!1},d=function(a){a.timeStamp=+new Date;a.target||(a.target=a.srcElement||this);a.pageX=a.clientX+document.documentElement.scrollLeft;a.pageY=a.clientY+document.documentElement.scrollTop;a.relatedTarget="mouseover"==a.type?a.fromElement:"mouseout"==a.type?a.toElement:null;for(var b=a.target,d=[];b.parentNode;)d.unshift(b.parentNode),b=b.parentNode;if(d.length&&c(a,d,Event.CAPTURING_PHASE)||
c(a,[a.target],Event.AT_TARGET)||d.length&&!1!==a.bubbles&&(d.reverse(),c(a,d,Event.BUBBLING_PHASE)))return a.returnValue;a.stopPropagation();return a.returnValue},e={addEventListener:function(b,c,e){var f=(this.__events||{})[b]||[],g=f.length;-1<a(f,c,e)||("__events"in this?f=this.__events:this.__events=f={_handler:d.bind(this)},b in f||(f[b]=[]),f[b].push({listener:c,useCapture:e}),g||this.attachEvent("on"+b,f._handler))},removeEventListener:function(b,c,d){var e=(this.__events||{})[b]||[];c=a(e,
c,d);-1!=c&&(e.splice(c,1),e.length||this.detachEvent("on"+b,this.__events._handler))},dispatchEvent:function(a){a.returnValue=!0;return d.call(this,a)}},f=[Element,window.constructor,document.constructor];for(;f.length;){var g=f.pop(),h;for(h in e)g.prototype[h]=e[h]}}})();
(function(){if(window.MouseEvent)try{new MouseEvent("click")}catch(a){var b=function(a,b){if(!arguments.length)throw Error("Not enough arguments");var e={type:a,bubbles:!1,cancelable:!1,view:window,detail:1,screenX:0,screenY:0,clientX:0,clientY:0,ctrlKey:!1,altLey:!1,shiftKey:!1,metaKey:!1,button:0,relatedTarget:null},f;for(f in b)e[f]=b[f];f=document.createEvent("MouseEvent");f.initMouseEvent(e.type,e.bubbles,e.cancelable,e.view,e.detail,e.screenX,e.screenY,e.clientX,e.clientY,e.ctrlKey,e.altKey,
e.shiftKey,e.metaKey,e.button,e.relatedTarget);return f};b.prototype=window.MouseEvent.prototype;window.MouseEvent=b}else window.MouseEvent=function(a,b){if(!arguments.length)throw Error("Not enough arguments");var e={type:a,cancelable:!1,bubbles:!1},f=document.createEventObject(),g;for(g in e)f[g]=e[g];for(g in b)f[g]=b[g];return f}})();
(function(){if(!window.CustomEvent&&document.createEventObject)window.CustomEvent=function(a,b){if(!arguments.length)throw Error("Not enough arguments");var e={type:a,bubbles:!1,cancelable:!1,detail:null},f=document.createEventObject(),g;for(g in e)f[g]=e[g];for(g in b)f[g]=b[g];return f};else try{new CustomEvent("test")}catch(a){var b=function(a,b){if(!arguments.length)throw Error("Not enough arguments");var e={bubbles:!1,cancelable:!1,detail:null},f;for(f in b)e[f]=b[f];f=document.createEvent("CustomEvent");
f.initCustomEvent(a,e.bubbles,e.cancelable,e.detail);return f};b.prototype=(window.CustomEvent||window.Event).prototype;window.CustomEvent=b}})();(function(){window.getSelection||document.addEventListener("readystatechange",function(a){"complete"==document.readyState&&(a=new CustomEvent("DOMContentLoaded"),document.dispatchEvent(a))})})();
window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){return setTimeout(a,1E3/60)};window.cancelAnimationFrame=window.cancelAnimationFrame||window.mozCancelAnimationFrame||window.webkitCancelAnimationFrame||window.oCancelAnimationFrame||window.msCancelAnimationFrame||function(a){return clearTimeout(a)};
(function(){if(!("ongesturechange"in window||!1 in window)){var a=0,b=0,c=!1,d=function(a,b){setTimeout(function(){b.dispatchEvent(a)},0)};document.addEventListener("touchstart",function(e){if(2==e.touches.length){var f=e.touches[0],g=e.touches[1],h=f.clientX-g.clientX,f=f.clientY-g.clientY;a=Math.sqrt(h*h+f*f);b=Math.atan2(f,h);c=!0;h=new CustomEvent("gesturestart",{bubbles:!0});d(h,e.target)}},!1);document.addEventListener("touchmove",function(c){if(2==c.touches.length){var f=c.touches[0],g=c.touches[1],
h=f.clientX-g.clientX,g=f.clientY-g.clientY,f=Math.sqrt(h*h+g*g),h=Math.atan2(g,h),g=new CustomEvent("gesturechange",{bubbles:!0});g.altKey=c.altKey;g.ctrlKey=c.ctrlKey;g.metaKey=c.metaKey;g.shiftKey=c.shiftKey;g.rotation=180/Math.PI*(h-b)%360;g.altKey=c.altKey;g.scale=f/a;d(g,c.target)}},!1);document.addEventListener("touchend",function(a){if(c){c=!1;var b=new CustomEvent("gestureend",{bubbles:!0});d(b,a.target)}},!1)}})();
